#!/bin/sh

### BEGIN INIT INFO
# Provides:          
# Required-Start:    
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: 
# Description:       
### END INIT INFO


[ -f /etc/default/rcS ] && . /etc/default/rcS
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PROGRAM=

test -x $PROGRAM || exit 0

case "$1" in
  start)
	echo "Starting Alsa"
	/usr/sbin/alsactl -E HOME=/var/run/alsa -s -n 19 -c rdaemon &
	;;
  stop)
	killall alsactl
	;;
  force-reload|restart)
	$0 start
	;;
  status)
	exit 0
	;;
  *)
	echo "Usage: "$0" {start|stop|restart|force-reload|status}"
	exit 1
esac

exit 0
