#!/bin/sh

### BEGIN INIT INFO
# Provides:          
# Required-Start:    
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: 
# Description:       
### END INIT INFO


[ -f /etc/default/rcS ] && . /etc/default/rcS
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PROGRAM=/usr/lib/bluez5/bluetooth/bluetoothd

test -x $PROGRAM || exit 0

case "$1" in
  start)
	echo "Enabling Bluetooth discoverable"

sleep 15
echo -e "\
power on\n\
discoverable on\n\
pairable on\n\
agent NoInputNoOutput\n\
show\n\
quit\n\
" | bluetoothctl

	;;
  stop)
	;;
  force-reload|restart)
	$0 start
	;;
  status)
	exit 0
	;;
  *)
	echo "Usage: "$0" {start|stop|restart|force-reload|status}"
	exit 1
esac

exit 0
